services:
  better-auth-mytutorial:
    container_name: better-auth-mytutorial
    image: postgres:latest
    volumes:
      - better-auth-mytutorial:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  better-auth-mytutorial:
    name: better-auth-mytutorial
